name: Deploy

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.ref }}

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.145.0

      - name: build
        run: hugo build --minify

      - name: copy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          protocol: ftps
